In [30]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
from functools import lru_cache
pd.set_option("display.float_format", lambda x: "%0.3f" % x)

Подготавливаем данные

In [31]:
@lru_cache
def read_data(path:str):
    return pd.read_excel(path)

data =read_data("Data/financial_loan.xlsx")
features = ["annual_income", "loan_amount", "int_rate", "home_ownership", 
            "purpose", "loan_status"]
data = data[features]
# data.rename(columns={"loan_amount": "loan_amount (RUB)"}, inplace= True)
data.rename(columns= {"loan_status": "is_loss"}, inplace= True)

russian_median_salary = 74_000 * 12
usa_median_salary = data["annual_income"].quantile()
russian_median_loan_ammount = 97_000
usa_median_loan_ammount = data["loan_amount"].quantile()
russian_median_rate = 0.17
usa_median_rate = data["int_rate"].quantile()

data["DTI"] = data["loan_amount"] / data["annual_income"]
data["annual_income_ru"] = russian_median_salary * (data["annual_income"] / usa_median_salary)
data["loan_ammount_ru"] = data["annual_income_ru"] * data["DTI"]
data["int_rate_ru"] = russian_median_rate * (data["int_rate"] / usa_median_rate)

#Преобразуем статус кредита в двоичный вид
data["is_loss"] = data["is_loss"].map({"Fully Paid": 0, "Charged Off": 1, "Current": 0})

#Сокращаем кол-во категорий для целей кредита
purpose_categories = ["Debt consolidation", "credit card", "small business", "major purchase", "vacation",
                     "house",  "car"]
data["purpose"] = data["purpose"].apply(lambda purpose: purpose if purpose in purpose_categories else "other")
data["home_ownership"] = data["home_ownership"].astype("category")
data["purpose"] = data["purpose"].astype("category")
data.describe()

C:\Users\PC12\AppData\Local\Temp\ipykernel_13712\2034794457.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data.rename(columns= {"loan_status": "is_loss"}, inplace= True)
C:\Users\PC12\AppData\Local\Temp\ipykernel_13712\2034794457.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data["DTI"] = data["loan_amount"] / data["annual_income"]
C:\Users\PC12\AppData\Local\Temp\ipykernel_13712\2034794457.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data["annual_income_ru"] = russian_median_salary * (data["annual_income"] / usa_median_salary)
C:\Users\PC12\AppData\Local\Temp\ipykernel_13712\2034794457.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data["loan_ammount_ru"] = data["annual_income_ru"] * data["DTI"]
C:\Users\PC12\AppData\Local\Temp\ipykernel_13712\2034794457.py:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data["int_rate_ru"] = russian_median_rate * (data["int_rate"] / usa_median_rate)
C:\Users\PC12\AppData\Local\Temp\ipykernel_13712\2034794457.py:25: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data["is_loss"] = data["is_loss"].map({"Fully Paid": 0, "Charged Off": 1, "Current": 0})
C:\Users\PC12\AppData\Local\Temp\ipykernel_13712\2034794457.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data["purpose"] = data["purpose"].apply(lambda purpose: purpose if purpose in purpose_categories else "other")
C:\Users\PC12\AppData\Local\Temp\ipykernel_13712\2034794457.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data["home_ownership"] = data["home_ownership"].astype("category")
C:\Users\PC12\AppData\Local\Temp\ipykernel_13712\2034794457.py:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data["purpose"] = data["purpose"].astype("category")

,annual_income,loan_amount,int_rate,is_loss,DTI,annual_income_ru,loan_ammount_ru,int_rate_ru
count,38576.000,38576.000,38576.000,38576.000,38576.000,38576.000,38576.000,38576.000
mean,69644.540,11296.067,0.120,0.138,0.187,1030739.197,167181.789,0.173
std,64293.681,7460.746,0.037,0.345,0.116,951546.479,110419.041,0.053
min,4000.000,500.000,0.054,0.000,0.001,59200.000,7400.000,0.078
25%,41500.000,5500.000,0.093,0.000,0.100,614200.000,81400.000,0.134
50%,60000.000,10000.000,0.119,0.000,0.165,888000.000,148000.000,0.170
75%,83200.500,15000.000,0.146,0.000,0.250,1231367.400,222000.000,0.209
max,6000000.000,35000.000,0.246,1.000,0.830,88800000.000,518000.000,0.352

Feature Engineering

In [ ]:
# def create_features(df):
#     df = df.copy()
#     # 1. Базовые отношения
#     df['monthly_payment'] = df['loan_ammount_ru'] * df['int_rate_ru'] / 100 / 12
#     df['payment_to_income'] = df['monthly_payment'] / (df['annual_income_ru'] / 12)
#     df['income_after_payment'] = df['annual_income_ru'] - df['monthly_payment'] * 12
    
#     # 2. Полиномиальные
#     df['income_loan_product'] = df['annual_income_ru'] * df['loan_ammount_ru']
#     df['income_rate_product'] = df['annual_income_ru'] * df['int_rate_ru']
#     df['loan_rate_product'] = df['loan_ammount_ru'] * df['int_rate_ru']
#     df['risk_composite'] = df['int_rate_ru'] * df['DTI']
    
#     # 3. Биннинг
#     df['dti_group'] = pd.cut(df['DTI'], 
#                              bins=[0, 0.3, 0.5, 0.7, 1.0, np.inf],
#                              labels=['safe', 'moderate', 'risky', 'very_risky', 'overloaded'])
    
#     df['income_group'] = pd.qcut(df['annual_income_ru'], q=5, 
#                                  labels=['very_low', 'low', 'medium', 'high', 'very_high'])
    
#     # 4. Статистические
#     for col in ['annual_income_ru', 'loan_ammount_ru', 'int_rate_ru', 'DTI']:
#         df[f'{col}_zscore'] = (df[col] - df[col].mean()) / df[col].std()
#         df[f'{col}_percentile'] = df[col].rank(pct=True)
    
#     # 5. Флаги риска
#     df['high_dti_flag'] = (df['DTI'] > 0.7).astype(int)
#     df['high_rate_flag'] = (df['int_rate_ru'] > 15).astype(int)
#     df['loan_gt_income_flag'] = (df['loan_ammount_ru'] > df['annual_income_ru']).astype(int)
#     df['critical_combination_flag'] = ((df['DTI'] > 0.5) & (df['int_rate_ru'] > 10)).astype(int)
#     return df
# data = create_features(data)

#Превращаем все признаки в отдельные столбцы (One-Hot encoding)
# def get_custom_dummies(column: str):
#     global data
#     processed_cols = pd.get_dummies(data[column])
#     data = pd.concat([data, processed_cols], axis = 1)
#     data.drop(column, inplace= True, axis= 1)
#     for column in processed_cols.columns:
#         data[column] = data[column].apply(lambda val: 1 if val else 0)

# #Для статуса владения жильем
# get_custom_dummies("home_ownership")
# drop_indexes = data[data["NONE"] == 1].index
# data.drop(drop_indexes, inplace= True)
# data.drop("NONE", inplace= True, axis = 1)

# #Для цели кредита
# get_custom_dummies("purpose")

In [32]:
data.describe()
# data

,annual_income,loan_amount,int_rate,is_loss,DTI,annual_income_ru,loan_ammount_ru,int_rate_ru
count,38576.000,38576.000,38576.000,38576.000,38576.000,38576.000,38576.000,38576.000
mean,69644.540,11296.067,0.120,0.138,0.187,1030739.197,167181.789,0.173
std,64293.681,7460.746,0.037,0.345,0.116,951546.479,110419.041,0.053
min,4000.000,500.000,0.054,0.000,0.001,59200.000,7400.000,0.078
25%,41500.000,5500.000,0.093,0.000,0.100,614200.000,81400.000,0.134
50%,60000.000,10000.000,0.119,0.000,0.165,888000.000,148000.000,0.170
75%,83200.500,15000.000,0.146,0.000,0.250,1231367.400,222000.000,0.209
max,6000000.000,35000.000,0.246,1.000,0.830,88800000.000,518000.000,0.352

Отображаем матрицу корреляции

In [12]:
# plt.figure(figsize=(10, 10))
# sns.heatmap(data.corr(), cmap="coolwarm", annot= True, fmt=".2f", square=True)

Записываем итоговый Датасет в специальный файл

In [33]:
#Удаляем пропущенные значения
indices_to_drop = data[data["home_ownership"] == "NONE"].index
data.drop(indices_to_drop, axis=0, inplace=True)
data.to_csv("Data/processed_data", index=False)

C:\Users\PC12\AppData\Local\Temp\ipykernel_13712\3634212872.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data.drop(indices_to_drop, axis=0, inplace=True)

In [34]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 38573 entries, 0 to 38575
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   annual_income     38573 non-null  float64
 1   loan_amount       38573 non-null  int64
 2   int_rate          38573 non-null  float64
 3   home_ownership    38573 non-null  category
 4   purpose           38573 non-null  category
 5   is_loss           38573 non-null  int64
 6   DTI               38573 non-null  float64
 7   annual_income_ru  38573 non-null  float64
 8   loan_ammount_ru   38573 non-null  float64
 9   int_rate_ru       38573 non-null  float64
dtypes: category(2), float64(6), int64(2)
memory usage: 2.7 MB