In [5]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from functools import lru_cache
pd.set_option("display.float_format", lambda x: "%0.3f" % x)

Подготавливаем числовые данные

In [6]:
@lru_cache
def read_data(path:str):
    return pd.read_excel(path)

data =read_data("Data/financial_loan.xlsx")
features = ["home_ownership", 
            "purpose", "annual_income", "int_rate", 
            "loan_amount", "loan_status"]
data = data[features]
# data.rename(columns={"loan_amount": "loan_amount (RUB)"}, inplace= True)
data.rename(columns= {"loan_status": "is_loss"}, inplace= True)

russian_median_salary = 74_000 * 12
usa_median_salary = data["annual_income"].quantile()
russian_median_loan_ammount = 97_000
usa_median_loan_ammount = data["loan_amount"].quantile()
russian_median_rate = 0.17
usa_median_rate = data["int_rate"].quantile()

data["DTI"] = data["loan_amount"] / data["annual_income"]
data["annual_income_ru"] = russian_median_salary * (data["annual_income"] / usa_median_salary)
data["loan_ammount_ru"] = data["annual_income_ru"] * data["DTI"]
data["int_rate_ru"] = russian_median_rate * (data["int_rate"] / usa_median_rate)
data.describe()

C:\Users\PC12\AppData\Local\Temp\ipykernel_19444\1554650895.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data.rename(columns= {"loan_status": "is_loss"}, inplace= True)
C:\Users\PC12\AppData\Local\Temp\ipykernel_19444\1554650895.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data["DTI"] = data["loan_amount"] / data["annual_income"]
C:\Users\PC12\AppData\Local\Temp\ipykernel_19444\1554650895.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data["annual_income_ru"] = russian_median_salary * (data["annual_income"] / usa_median_salary)
C:\Users\PC12\AppData\Local\Temp\ipykernel_19444\1554650895.py:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data["loan_ammount_ru"] = data["annual_income_ru"] * data["DTI"]
C:\Users\PC12\AppData\Local\Temp\ipykernel_19444\1554650895.py:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data["int_rate_ru"] = russian_median_rate * (data["int_rate"] / usa_median_rate)

,annual_income,int_rate,loan_amount,DTI,annual_income_ru,loan_ammount_ru,int_rate_ru
count,38576.000,38576.000,38576.000,38576.000,38576.000,38576.000,38576.000
mean,69644.540,0.120,11296.067,0.187,1030739.197,167181.789,0.173
std,64293.681,0.037,7460.746,0.116,951546.479,110419.041,0.053
min,4000.000,0.054,500.000,0.001,59200.000,7400.000,0.078
25%,41500.000,0.093,5500.000,0.100,614200.000,81400.000,0.134
50%,60000.000,0.119,10000.000,0.165,888000.000,148000.000,0.170
75%,83200.500,0.146,15000.000,0.250,1231367.400,222000.000,0.209
max,6000000.000,0.246,35000.000,0.830,88800000.000,518000.000,0.352

Подготавливаем категориальные данные

In [7]:
#Преобразуем статус кредита в двоичный вид
data["is_loss"] = data["is_loss"].map({"Fully Paid": 0, "Charged Off": 1, "Current": 0})

#Сокращаем кол-во категорий для целей кредита
purpose_categories = ["Debt consolidation", "credit card", "small business", "major purchase", "vacation",
                     "house",  "car"]
data["purpose"] = data["purpose"].apply(lambda purpose: purpose if purpose in purpose_categories else "other")

#Превращаем все признаки в отдельные столбцы (One-Hot encoding)
# def get_custom_dummies(column: str):
#     global data
#     processed_cols = pd.get_dummies(data[column])
#     data = pd.concat([data, processed_cols], axis = 1)
#     data.drop(column, inplace= True, axis= 1)
#     for column in processed_cols.columns:
#         data[column] = data[column].apply(lambda val: 1 if val else 0)

# #Для статуса владения жильем
# get_custom_dummies("home_ownership")
# drop_indexes = data[data["NONE"] == 1].index
# data.drop(drop_indexes, inplace= True)
# data.drop("NONE", inplace= True, axis = 1)

# #Для цели кредита
# get_custom_dummies("purpose")

C:\Users\PC12\AppData\Local\Temp\ipykernel_19444\2183177877.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data["is_loss"] = data["is_loss"].map({"Fully Paid": 0, "Charged Off": 1, "Current": 0})
C:\Users\PC12\AppData\Local\Temp\ipykernel_19444\2183177877.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data["purpose"] = data["purpose"].apply(lambda purpose: purpose if purpose in purpose_categories else "other")

In [8]:
data.describe()
# data

,annual_income,int_rate,loan_amount,is_loss,DTI,annual_income_ru,loan_ammount_ru,int_rate_ru
count,38576.000,38576.000,38576.000,38576.000,38576.000,38576.000,38576.000,38576.000
mean,69644.540,0.120,11296.067,0.138,0.187,1030739.197,167181.789,0.173
std,64293.681,0.037,7460.746,0.345,0.116,951546.479,110419.041,0.053
min,4000.000,0.054,500.000,0.000,0.001,59200.000,7400.000,0.078
25%,41500.000,0.093,5500.000,0.000,0.100,614200.000,81400.000,0.134
50%,60000.000,0.119,10000.000,0.000,0.165,888000.000,148000.000,0.170
75%,83200.500,0.146,15000.000,0.000,0.250,1231367.400,222000.000,0.209
max,6000000.000,0.246,35000.000,1.000,0.830,88800000.000,518000.000,0.352

Отображаем матрицу корреляции

In [9]:
# plt.figure(figsize=(10, 10))
# sns.heatmap(data.corr(), cmap="coolwarm", annot= True, fmt=".2f", square=True)

Записываем итоговый Датасет в специальный файл

In [10]:
#Удаляем пропущенные значения
indices_to_drop = data[data["home_ownership"] == "NONE"].index
data.drop(indices_to_drop, axis=0, inplace=True)
data.to_csv("Data/processed_data", index=False)

C:\Users\PC12\AppData\Local\Temp\ipykernel_19444\3634212872.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data.drop(indices_to_drop, axis=0, inplace=True)

In [11]:
data.describe()

,annual_income,int_rate,loan_amount,is_loss,DTI,annual_income_ru,loan_ammount_ru,int_rate_ru
count,38573.000,38573.000,38573.000,38573.000,38573.000,38573.000,38573.000,38573.000
mean,69643.678,0.120,11296.510,0.138,0.187,1030726.433,167188.346,0.173
std,64295.030,0.037,7460.815,0.345,0.116,951566.450,110420.067,0.053
min,4000.000,0.054,500.000,0.000,0.001,59200.000,7400.000,0.078
25%,41500.000,0.093,5500.000,0.000,0.100,614200.000,81400.000,0.134
50%,60000.000,0.119,10000.000,0.000,0.165,888000.000,148000.000,0.170
75%,83200.000,0.146,15000.000,0.000,0.250,1231360.000,222000.000,0.209
max,6000000.000,0.246,35000.000,1.000,0.830,88800000.000,518000.000,0.352