In [ ]:
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import precision_score, recall_score, fbeta_score
from joblib import dump
import numpy as np
pd.set_option("display.float_format", lambda x: "%0.3f" % x)
np.set_printoptions(suppress=True)

def print_line(): print("-" * 15)

In [2]:
data = pd.read_csv("Data/processed_data")
data

,home_ownership,purpose,annual_income,int_rate,loan_amount,is_loss,DTI_USD,annual_income_ru,loan_ammount_ru,int_rate_ru
0,RENT,car,30000.000,0.153,2500,1,0.083,444000.000,37000.000,0.219
1,RENT,car,48000.000,0.186,3000,0,0.062,710400.000,44400.000,0.267
2,RENT,car,50000.000,0.160,12000,1,0.240,740000.000,177600.000,0.229
3,MORTGAGE,car,42000.000,0.106,4500,0,0.107,621600.000,66600.000,0.153
4,MORTGAGE,car,83000.000,0.060,3500,0,0.042,1228400.000,51800.000,0.086
...,...,...,...,...,...,...,...,...,...,...
38571,MORTGAGE,other,100000.000,0.130,24250,0,0.242,1480000.000,358900.000,0.186
38572,RENT,other,50000.000,0.135,25200,0,0.504,740000.000,372960.000,0.193
38573,RENT,other,65000.000,0.175,25000,0,0.385,962000.000,370000.000,0.251
38574,RENT,other,368000.000,0.182,24000,0,0.065,5446400.000,355200.000,0.262
38575,RENT,other,80000.000,0.210,18000,0,0.225,1184000.000,266400.000,0.301

In [4]:
X = data.drop("is_loss", axis= 1)
Y = data["is_loss"]
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.25, random_state=42, stratify=Y)
Y_train = pd.DataFrame(Y_train)
Y_test = pd.DataFrame(Y_test)
print(f"X_train: {X_train.shape}\nX_test: {X_test.shape}\nY_train: {Y_train.shape}\nY_test: {Y_test.shape}")

X_train: (28932, 9)
X_test: (9644, 9)
Y_train: (28932, 1)
Y_test: (9644, 1)

Преобразуем числовые данные в единый масштаб (Нормализация). Долго (Заменено готовой библиотекой)

In [ ]:
# X_train_norm = X_train.copy()
# X_test_norm = X_test.copy()
# for col in X_train.columns[:3]:
#     X_train_norm[col] = X_train_norm[col].apply(lambda val: (val - min) / (max - min))[col]
#     X_test_norm[col] = X_test_norm[col].apply(lambda val: (val - min) / (max - min))[col]
# X_train_norm.to_csv("Data/X_train_norm", index= False)
# X_test_norm.to_csv("Data/X_test_norm", index= False)

In [ ]:
# X_train_norm = pd.read_csv("Data/X_train_norm")
# X_test_norm = pd.read_csv("Data/X_test_norm")

In [ ]:
# model = RandomForestClassifier(n_estimators= 100, max_depth= 4,
#                                random_state=42,
#                                class_weight=dict(enumerate(class_weights)))

---------------
[0.58022785 3.616125  ]
Recall на тренировочных данных: 0.7025
---------------
Recall на тестовых данных: 0.6901725431357839
---------------
Precision на тесте: 0.2039459099977832
---------------
                feature  importance
1              int_rate       0.588
0   Montly income (RUB)       0.125
13       small business       0.104
2     loan_amount (RUB)       0.099
9           credit card       0.040
11       major purchase       0.011
3              MORTGAGE       0.007
6                  RENT       0.006
8                   car       0.005
5                   OWN       0.004
7    Debt consolidation       0.004
12                other       0.003
4                 OTHER       0.002
10                house       0.001
14             vacation       0.001

Подбираем лучшие параметры для модели (ОЧЕНЬ ДОЛГО). Результат: n_estimators = 106, max_depth = 4 (Заменено библиотекой)

In [ ]:
# best_f = 0
# for estimators in range(10, 150, 3):
#     for depth in range(3, 15):
#         test_model = RandomForestClassifier(n_estimators=estimators, max_depth= depth, 
#                                             random_state=42,
#                                             class_weight=dict(enumerate(class_weights)))
#         test_model.fit(X_train_norm, Y_train)
#         f_score = fbeta_score(Y_test, test_model.predict(X_test_norm), beta=1.5)
#         if f_score > best_f:
#             best_f = f_score
#             best_estimators = estimators
#             best_max_depth = depth

# print(f"Лучший параметр estimators: {best_estimators}\nЛучший параметр max_depth: {best_max_depth}")

In [ ]:
# prediction = model.predict(X_test)
# prediction = pd.DataFrame(prediction, columns=['Prediction'])
# results = pd.concat([X_test, prediction["Prediction"], Y_test], axis= 1, join="inner")
# results.rename(columns={"is_loss": "Real Value"}, inplace= True) 
# results[(results["Real Value"] == 1) & (results["Prediction"] == 1)]

,Montly income (RUB),int_rate,loan_amount (RUB),MORTGAGE,OTHER,OWN,RENT,Debt consolidation,car,credit card,house,major purchase,other,small business,vacation,Prediction,Real Value
7,64892,0.160,400000,0,0,0,1,0,0,0,0,0,1,0,0,1,1
8,85551,0.153,1824000,0,0,0,1,1,0,0,0,0,0,0,0,1,1
27,171102,0.197,2800000,1,0,0,0,0,0,0,0,0,1,0,0,1,1
40,53231,0.168,1200000,0,0,0,1,1,0,0,0,0,0,0,0,1,1
43,49429,0.146,1024000,0,0,0,1,0,0,1,0,0,0,0,0,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9591,152091,0.160,1200000,1,0,0,0,0,0,0,1,0,0,0,0,1,1
9596,115335,0.217,2588000,1,0,0,0,0,0,0,0,0,1,0,0,1,1
9622,101394,0.175,2800000,0,0,0,1,0,0,0,0,0,0,1,0,1,1
9631,73003,0.119,960000,0,0,0,1,0,0,0,0,0,1,0,0,1,1
9639,76045,0.138,2000000,0,0,0,1,1,0,0,0,0,0,0,0,1,1

In [10]:
model_path = "models/RandomForest.sav"
dump(model, model_path)

['models/RandomForest.sav']